### ISSUE TITLE
[REVIEW] Identifying Emotional States using Keystroke Dynamics

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#28]
### Paper Details
**Link**: http://hci.usask.ca/uploads/203-p715-epp.pdf
**Date**: may 2011
**Topic**:  Identifying Emotional States using Keystroke Dynamics

**Comment by yuvalkh** [comment]
- describing emotions
- features to take from keyboard
- data collecting such as a questionnaire asking the users his emotions while testing
- content features(might not want to enter it because of privacy)
- focus on fixed text and not on free text
- personalized and aggregate models( they did aggregate in the experiments)

**Comment by yuvalkh** [comment]
Didn't use that paper in the work.
