### ISSUE TITLE
[REVIEW] Your Keystrokes Can Reveal Who You Are — And How You Feel

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/Research#33]
### Paper Details
**Link**: https://www.vocativ.com/428550/keystrokes-reveal-identity-machine-learning-data/index.html
**Date**: May 2017
**Topic**: how you feel using keyboard strokes

**Comment by yuvalkh** [comment]
- Can identify who is using the pc by the way he types.
- Can ask the users how they feel and then tell them how they feel later instead of identify who are they.
- Doesn't explain how it is done except of watching delay between keys and duration of each key press.
- **Might want to further see this article to see important links**

**Comment by yuvalkh** [comment]
Didn't use that paper in the work.
