### ISSUE TITLE
[REVIEW] The influence of emotion on keyboard typing: an experimental study using visual stimuli

### ISSUE THREAD

**Issue by Zshoham** [capi-bgu/Research#37]
### Paper Details
**Link**: https://biomedical-engineering-online.biomedcentral.com/articles/10.1186/1475-925X-13-81
**Date**: 2014
**Topic**: Study of keyboard features that are affected by emotion

**Comment by hodTwito** [comment]
Notes:
- This study aims to examine the source of variance in keystroke typing patterns caused by emotions.
- features suggestions (Conclusions)
- the history of the key strokes based emotion detection field and some accuracy results- worth reading into (Background)
- SAM-  Self-Assessment Manikin: affective rating system devised by Lang PJ, used to acquire the affective ratings.
- Influence of emotion on different features- important
- this paper used traditional statistical methods instead of sophisticated ML algorithms
